(define (bissextile? a) (if (and (= (modulo a 4) 0)
                                 (or (not (= (modulo a 100) 0))
                                     (= (modulo a 400) 0)))
                            #t
                            #f))
(define (nb-annees-bissextiles a) (if (>= a 1900)
                                     (+ (if (bissextile? a)
                                            1
                                            0)
                                        (nb-annees-bissextiles (- a 1))) 0))
(define nbjours (list 0 31 28 31 30 31 30 31 31 30 31 30 31))
(define nbjoursbis (list 0 31 29 31 30 31 30 31 31 30 31 30 31))
(define jours (list "Lundi" "Mardi" "Mercredi" "Jeudi" "Vendredi" "Samedi" "Dimanche"))
(define (nb-jours-au-1-jan m) (if (= m 1)
                                      (list-ref nbjours (- m 1))
                                      (+ (list-ref nbjours (- m 1))
                                             (nb-jours-au-1-jan (- m 1)))))                                  
(define (nb-jours-au-1-jan-bis m) (if (= m 1)
                                      (list-ref nbjoursbis (- m 1))
                                      (+ (list-ref nbjoursbis (- m 1))
                                             (nb-jours-au-1-jan-bis (- m 1)))))
(define (nb-jours j m a) (if (>= a 1900)
                             (if (bissextile? a)
                                 (+ (- j 1) (nb-jours-au-1-jan-bis m) (nb-jours 1 13 (- a 1)))
                                 (+ (- j 1) (nb-jours-au-1-jan m) (nb-jours 1 13 (- a 1))))
                             0))
(define (jour-de-semaine j m a) (let ((j (modulo (nb-jours j m a) 7))) (list-ref jours j)))