(require (lib "turtles.ss" "graphics"))

(define (von_koch prof a) (cond ((= prof 0) a)
                                (else (von_koch (- prof 1) (/ a 3)))))
(define (prepa_vk) (begin (clear) (move (- 300))))
(define (draw_vk_t index a) (cond ((> index 0) (begin (draw_vk_t (- index 1) a)
                                                    (turn 60) (draw_vk_t (- index 1) a)
                                                    (turn (- 120)) (draw_vk_t (- index 1) a)
                                                    (turn 60) (draw_vk_t (- index 1) a)))
                                  (else (draw a))))
(define (draw_vk_c index a) (cond ((> index 0) (begin (draw_vk_c (- index 1) a)
                                                    (turn 90) (draw_vk_c (- index 1) a)
                                                    (turn (- 90)) (draw_vk_c (- index 1) a)
                                                    (turn (- 90)) (draw_vk_c (- index 1) a)
                                                    (turn 90) (draw_vk_c (- index 1) a)))
                                  (else (draw a))))
(define (anim_vk_t n i) (cond ((>= n 0) (begin (prepa_vk)
                                             (draw_vk_t i (von_koch 500))
                                             (anim_vk_t (- n 1) (+ i 1))))))
(define (anim_vk_c n i) (cond ((>= n 0) (begin (prepa_vk)
                                             (draw_vk_c i (von_koch i 500))
                                             (anim_vk_c (- n 1) (+ i 1))))))
(define (anime_vk_t n) (begin (turtles #t)
                            (anim_vk_t n 0)))
(define (anime_vk_c n) (begin (turtles #t)
                            (anim_vk_c n 0)))